### ISSUE TITLE
Spec DSL

### ISSUE THREAD

**Issue by teoljungberg** [teoljungberg/tunit#2]
The result should work something like this:

``` ruby
describe MyThing do
  before do
    self.blah = Blah.new
  end
  attr_accessor :blah

  describe '#the_ultimate_answer' do
    it 'is decidedly so' do
      assert_equal 42, blah.the_ultimate_answer
    end
  end

  describe '#packing_list' do
    it 'consists of a towel' do
      assert_includes blah.packing_list, "towel"
    end
  end
end
```
# TODO
- [x] Add it blocks
- [x] Add before filter
- [x] Add after filter
- [x]  Add describe blocks
- [x] Add nested describe blocks
- [x] fix failing on empty specs
